### ISSUE TITLE
False duplicates

### ISSUE THREAD

**Issue by RDominique** [PaulLereverend/NextcloudDuplicateFinder#20]
The app is giving false duplicates.
Steps to recreate issue:

1. user2 shares folder1 to user1
2. user2 creates or uploads file1 in folder1
3. user2 shares file1 to user 1 (I know this is silly, but really, some users do things like this)
4. user1 executes DuplicateFinder
5. the app finds duplicate file1 (one in home folder and one in folder1)
6. on removing one of the two duplicates the other is deleted also by accident

Doesn't the Nextcloud database has a unique id for each file? Maybe compare that id between found duplicates to filter out the false duplicates?

Thanks in advance.

**Comment by graphius** [comment]
This may be the issue I am having as well. I get a lot of "duplicates" found, but the path and filename for each file is exactly the same. If I delete one of the two, it deletes both copies (as there really is only one file).
If I recover the file from the trash bin, it does not seem to be found by the app again.

**Comment by chrros95** [comment]
Thanks for sharing this.
As this issue was opened in February and some releases have been published, I may ask you which version you are using?
Please upgrade to this version, if you're not using the latest version (0.0.11).
Please consider as well, to clean all duplicates by running `/occ duplicates:clear`

Restoring files from trash have indeed not been tested, so they might not show up directly. But they should be visible after the background is completed (runs every 5 days). If you don't like to wait please be advised to run `./occ duplicates:find-all`

**Comment by graphius** [comment]
I ran `occ duplicates:clear `then reran `occ duplicates:find-all` this seems to have fixed the issue.
I am using version 0.0.11

**Comment by RDominique** [comment]
I can confirm. Using version 0.0.11 and after running `occ duplicates:clear`, the issue is gone.
Thanks a lot for the follow-up!
Issue closed.
