### ISSUE TITLE
Open the Results

### ISSUE THREAD

**Issue by renatomportugal** [PaulLereverend/NextcloudDuplicateFinder#3]
Hello brother... In the screen os results, would be nice if with one click, open the results, to see if they are corrupted, or if the owner had a doubt, to remember the content. The alternative solution for now is copy the name to the program search. Think about please. Thanks.

**Comment by miceno** [comment]
I am interested on this feature, so I first thought to add a link to open every document, but then I thought it would be enough to add a link to its containing folder, and users will decide what to do about the file.

Another way to deal with it will be adding an icon to the right of the file to download it (see `icon-download`), another to show the containing the folder (see `icon-files-dark`) and so on... I prefer this approach, since it is extensible for any other one to add a new icon with a new feature.

**Comment by miceno** [comment]
@PaulLereverend what do you think? Should I try to add more icons for options? Did you consider it before?

I would not like to do something that will break the look and feel.

**Comment by PaulLereverend** [comment]
Done in : 8d1bafb
