### ISSUE TITLE
Enabled encryption support

### ISSUE THREAD

**Issue by andyxheli** [PaulLereverend/NextcloudDuplicateFinder#33]
Hello currently when running the below commend not running. Will there be encryption support for this app 
sudo -u www-data php occ duplicates:find-all
Encryption is enabled. Aborted.

**Comment by chrros95** [comment]
Encryption is officially not yet supported because nobody tested it yet.
But since version 0.0.9 the mechanism for that should be implemented.

So, please feel free to test it.

You can do this by either simply upload/create a new duplicate or comment out the following code to find all duplicates
https://github.com/PaulLereverend/NextcloudDuplicateFinder/blob/6068efd9d54539c0daec4b02c54685706f45000b/lib/Command/FindDuplicates.php#L98-L101

You're welcome to hand in any exceptions/errors that occur

**Comment by sfatula** [comment]
For me it does not work with encryption. If I take a sha1sum of the 2 encrypted photos, they are different. However, if I decrypt them (download the 2 files) and then sha1sum them, they are the same. So, it appears the files have to be decrypted before taking the sha1 hash.

**Comment by chrros95** [comment]
I'm not sure if I understand your comment right, @sfatula.
Computing the hash sums of two (good) encrypted, identical files should newer result in the same.
On the opposite two unencrypted identical files should result in the same hash. Your comment basically describes this behaviour 

To solve challenges like this, the app utilizes the functionality of the Nextcloud server core which decrypts the stream while reading/hashing it (s. https://github.com/nextcloud/server/blob/9187e986e10a0e189f825cd462eb9e68bd732981/lib/private/Files/Storage/Wrapper/Encryption.php#L832)

So if you view the result in the app, are they equal (sha256 is used)?

**Comment by sfatula** [comment]
No, they are different. As I said, I took the sha256 checksum of two encrypted photos. Both originals were encrypted by Nextcloud, and the sha256 checksums were in fact different. I have hundreds of duplicates due to how dumb nextcloud client app is. If I unencrypt those files and take the sha256 checksum, they are identical. I don't know what else to tell you. Just reporting how it worked as you asked. And no, your app detects zero duplicates even though one device uploaded all the photos twice. 

I understand you believe they should be the same. I don't know how they get encrypted. I know my user key is part of the encryption, not sure what else is have not reviewed the nextcloud code. 

The point is, using nextcloud encryption with user keys, this plugins never detects any duplicates. Don't know why.
